RDKC-7522 : RDK Camera Yocto build failures.
Reason for change: Solved undefined reference to `PRO_GetStr' error.
Test Procedure: None
Risks: None

Signed-off-by: rnaray004c <Rajkumar_Narayanan@comcast.com>
(cherry picked from commit 924931158f3d21f7a95815d26516193ed54398ec)
Change-Id: Ie69a0a758f4f01348d65dec9386cc94a0a451f3e