REFPLTCAM-65: libconfigmgr.so: undefined reference to `PRO_GetStr'
Reason for change: Moved Configmgr changes from rdk-next branch into yocto-dunfell-upgrade branch
Test Procedure: None
Risks: None

Signed-off-by: e.savidha <e.savidha@ltts.com>
Change-Id: I869aa1d65cf43def7c08f7995fb8f984d531eb83